### ISSUE TITLE
lufi: raptor not found while using reverse proxy

### ISSUE THREAD

**Issue by Wonderfall** [xataz/dockerfiles#31]
Here is my nginx configuration, it used to work with other services : 

```
server {
  listen 8000;
  server_name up.targaryen.house;
  return 301 https://$host$request_uri;
}

server {
  listen 4430 ssl http2;
  server_name up.targaryen.house;

  ssl_certificate /certs/targaryen.house.crt;
  ssl_certificate_key /certs/targaryen.house.key;

  include /etc/nginx/conf/ssl_params;
  include /etc/nginx/conf/headers_params;

  add_header Strict-Transport-Security "max-age=31536000;includeSubDomains;preload";
  client_max_body_size 250M;

  #auth_basic "Who's this?";
  #auth_basic_user_file /passwds/<NAME>.htpasswd;

  location / {
    proxy_pass http://lufi:8080;
    include /etc/nginx/conf/proxy_params;
  }
}
```

What's wrong? Any idea? Google is not helping a lot on this one.
And there's no logs from lufi, nginx, just a page saying "Raptor not found".

**Comment by xataz** [comment]
No error for me.
What is the contents of proxy_params and headers_params ?

**Comment by Wonderfall** [comment]
Files are provided here : https://github.com/Wonderfall/dockerfiles/tree/master/boring-nginx

**Comment by ovizii** [comment]
Any updates? just hit the same problem.

**Comment by PixiBixi** [comment]
J'ai le même pb D:

**Comment by xataz** [comment]
C'est ouf, j'arrive pas à reproduire cette putain d'erreur.
@PixiBixi Pourrais tu me filer la configuration de ton reverse proxy ?

**Comment by PixiBixi** [comment]
Ca vient pas du reverse-proxy hein, j'ai même l'erreur quand je curl 127.0.0.1:8080/

D'ailleurs, y'a un pb bizarre sur le hub Docker.

Si on check ton Dockerfile du Hub, on voit FROM jessie, et pourtant, c'est bien ton Dockerfile avec Alpine qui est utilisé ? oO

**Comment by xataz** [comment]
```shell
docker exec -ti 8b4 ls /usr/lufi/local/lib/perl5/Mojolicious/resources/public/
favicon.ico  mojo
```

**Comment by PixiBixi** [comment]
Hmm on a bien pareil.

curl 127.0.0.1:8080/ et ton lufi.conf ?

**Comment by xataz** [comment]
Le curl me retourne bien la page, et le lufi est par défaut : 
```shell
docker exec -ti 8b4 cat /usr/lufi/lufi.conf
{
    hypnotoad => {
        listen => ['http://0.0.0.0:8080'],
        proxy  => 1,
    },
    contact             => 'contact@domain.tld',
    secrets             => ['XXXXXXXXXXXXXXXXXXXXXXXXXx'],
    theme               => 'default',
    length              => 8,
    provis_step         => 5,
    provisioning        => 100,
    token_length        => 32,
    max_file_size       => 1000000000,
    default_delay       => 1,
    max_delay           => 0,
    prefix              => '/',
    db_path             => '/usr/lufi/data/lufi.db',
    upload_dir          => '/usr/lufi/files',
};
```

**Comment by PixiBixi** [comment]
j'peux avoir tes logs de build ?

**Comment by xataz** [comment]
La j'ai pas rebuild, j'ai pris ce qu'il y avais sur le hub.
Mais y'a effectivement des erreurs lors du build, du à musl, mais je colmate ceci avec l'installation des modules perl depuis apk.

**Comment by PixiBixi** [comment]
hmm je vais essayer ta comande sans docker-compose voir

**Comment by PixiBixi** [comment]
Ok alors c'est très étonnant...

```
  lufi:
    image: xataz/lufi
    container_name: lufi
    restart: always
    environment:
      - VIRTUAL_HOST=images.x.fr
      - LETSENCRYPT_HOST=images.x.fr
      - LETSENCRYPT_EMAIL=contact@x.fr
      - UID=1001
      - GID=1001
      - WEBROOT=/
      - SECRET=702bba32208b40d2e2166de96b58ff19
      - CONTACT=contact+lufi@x.fr
      - MAX_FILE_SIZE=250000000
    volumes:
      - /root/files/apps/lufi/data:/data
      - /root/files/apps/lufi/files:/files
```

Avec ça, ça marche

On dirait que tu as mal définit une var par défaut ?
