### ISSUE TITLE
rutorrent-rtorrent - Error opening terminal: unknown.

### ISSUE THREAD

**Issue by onedr0p** [xataz/dockerfiles#38]
Docker Compose:

```yaml
  rutorrent-rtorrent:
    image: xataz/rtorrent-rutorrent
    container_name: rutorrent-rtorrent
    ports:
      - "6000:8080"
      - "5000:5000"
      - "50001:50001"
      - "50002:50002"
      - "50003:50003"
      - "50004:50004"
      - "50005:50005"
      - "50006:50006"
    volumes:
      - /home/docker/rutorrent-rtorrent/config:/config
      - /home/docker/rutorrent-rtorrent/data:/data
      - /mnt/scratch/Downloads/torrents:/mnt/scratch/Downloads/torrents
    mem_limit: 2048M
    environment:
      - WEBROOT=/rutorrent
      - UID=1012
      - GID=1003
    networks:
      serenity:
        ipv4_address: 172.18.0.125
    restart: always
```

.rtorrent.rc
```
scgi_port = 0.0.0.0:5000
encoding_list = UTF-8
port_range = 50001-50006
port_random = no
check_hash = no
directory = /mnt/scratch/Downloads/torrents/inter
session = /data/.session
encryption = allow_incoming, try_outgoing, enable_retry
use_udp_trackers = yes
dht = off
peer_exchange = no
min_peers = 10
max_peers = 100
min_peers_seed = 10
max_peers_seed = 50
max_uploads = 10
download_rate = 8500
upload_rate = 6000
max_memory_usage = 2500M
system.file_allocate.set = yes

execute = {sh,-c,/usr/bin/php /nginx/www/html/torrent/php/initplugins.php torrent &}
schedule = watch_directory,1,1,"load_start=/data/.watch/*.torrent"
schedule = untied_directory,5,5,"stop_untied=/data/.watch/*.torrent"
schedule = espace_disque_insuffisant,1,30,close_low_diskspace=500M

system.method.insert = d.get_finished_dir, simple, "cat=/mnt/scratch/Downloads/torrents/dst/,$d.get_custom1="
system.method.set_key = event.download.finished, move_complete, "d.set_directory=$d.get_finished_dir=;execute=mkdir,-p,$d.get_finished_dir=;execute=mv,-u,$d.get_base_path=,$d.get_finished_dir="
method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.get_base_path="
```

The Error I recieve in the console:
```
rm: '/var/www/html/rutorrent/conf' is a directory
rm: '/var/www/html/rutorrent/share' is a directory
Cannot load Zend OPcache - it was already loaded
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
Error opening terminal: unknown.
```
